{
    "openapi": "3.0.0",
    "info": {
        "title": "API REST Gestión de Citas",
        "version": "1.0.0"
    },
    "paths": {
        "/doctors": {
            "get": {
                "summary": "Obtiene todos los doctores",
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Doctor"
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": [
                                            {
                                                "id_profesional": 1,
                                                "nombre": "Juan",
                                                "apellido": "Pérez",
                                                "correo": "juan.perez@example.com",
                                                "id_especialidad": 2,
                                                "consultorio": 201
                                            },
                                            {
                                                "id_profesional": 2,
                                                "nombre": "Ana",
                                                "apellido": "Gómez",
                                                "correo": "ana.gomez@example.com",
                                                "id_especialidad": 5,
                                                "consultorio": 204
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener los doctores"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "/doctors/crear": {
            "post": {
                "summary": "Crea un nuevo doctor",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Doctor"
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "nombre": "Carlos",
                                        "apellido": "Rodríguez",
                                        "correo": "carlos.rodriguez@example.com",
                                        "id_especialidad": 3,
                                        "consultorio": 201
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                      "description": "Doctor creado exitosamente",
                      "content": {
                        "application/json": {
                          "schema": {
                            "$ref": "#/components/schemas/Doctor"
                          },
                          "examples": {
                            "example-1": {
                              "value": {
                                "id_profesional": 3,
                                "nombre": "Carlos",
                                "apellido": "Rodríguez",
                                "correo": "carlos.rodriguez@example.com",
                                "id_especialidad": 3,
                                "consultorio": 201
                              }
                            }
                          }
                        }
                      }
                    },
                    "400": {
                      "description": "Consultorio duplicado o correo no válido",
                      "content": {
                        "application/json": {
                          "examples": {
                            "example-1": {
                              "value": {
                                "message": "El consultorio ya está en uso por otro doctor."
                              }
                            },
                            "example-2": {
                              "value": {
                                "message": "Correo no válido"
                              }
                            }
                          }
                        }
                      }
                    },
                    "500": {
                      "description": "Error del servidor",
                      "content": {
                        "application/json": {
                          "examples": {
                            "example-1": {
                              "value": {
                                "message": "Hubo un error al crear el doctor"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
             }
        },
        "/doctors/{id}": {
            "get": {
                "summary": "Obtiene un doctor por ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID del doctor",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Doctor"
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "id_profesional": 1,
                                            "nombre": "Juan",
                                            "apellido": "Pérez",
                                            "correo": "juan.perez@example.com",
                                            "id_especialidad": 2,
                                            "consultorio": 201
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Doctor no encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Doctor no encontrado"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener el doctor"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Actualiza un doctor",
                "parameters": [
                  {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "description": "ID del doctor",
                    "schema": {
                      "type": "integer"
                    }
                  }
                ],
                "requestBody": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Doctor"
                      },
                      "examples": {
                        "example-1": {
                          "value": {
                            "nombre": "Juan Actualizado",
                            "apellido": "Pérez Actualizado",
                            "correo": "juan.perez.actualizado@example.com",
                            "id_especialidad": 7,
                            "consultorio": 207
                          }
                        }
                      }
                    }
                  },
                  "required": true
                },
                "responses": {
                  "200": {
                    "description": "Doctor actualizado exitosamente",
                    "content": {
                      "application/json": {
                        "schema": {
                          "$ref": "#/components/schemas/Doctor"
                        },
                        "examples": {
                          "example-1": {
                            "value": {
                              "id_profesional": 1,
                              "nombre": "Juan Actualizado",
                              "apellido": "Pérez Actualizado",
                              "correo": "juan.perez.actualizado@example.com",
                              "id_especialidad": 7,
                              "consultorio": 207
                            }
                          }
                        }
                      }
                    }
                  },
                  "404": {
                    "description": "Doctor no encontrado",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Doctor no encontrado"
                            }
                          }
                        }
                      }
                    }
                  },
                  "400": {
                    "description": "Consultorio duplicado o correo no válido",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "El consultorio ya está en uso por otro doctor."
                            }
                          },
                          "example-2": {
                            "value": {
                              "message": "Correo no válido"
                            }
                          }
                        }
                      }
                    }
                  },
                  "500": {
                    "description": "Error del servidor",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Hubo un error al actualizar el doctor"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
            "delete": {
                "summary": "Elimina un doctor",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID del doctor",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Doctor eliminado exitosamente",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Doctor eliminado exitosamente"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Doctor no encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Doctor no encontrado"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al eliminar el doctor"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/pacientes": {
            "get": {
                "summary": "Obtiene todos los pacientes",
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Paciente"
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": [
                                            {
                                                "id_numeroCedula": 123,
                                                "nombre": "Pedro",
                                                "apellido": "García",
                                                "telefono": "1234567890",
                                                "fecha_nacimiento": "1990-01-01"
                                            },
                                            {
                                                "id_numeroCedula": 321,
                                                "nombre": "María",
                                                "apellido": "López",
                                                "telefono": "0987654321",
                                                "fecha_nacimiento": "1995-01-01"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener los pacientes"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },  
        "/pacientes/crear": {
            "post": {
                "summary": "Crea un nuevo paciente",
                "requestBody": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Paciente"
                      },
                      "examples": {
                        "example-1": {
                          "value": {
                            "id_numeroCedula": 311,
                            "nombre": "Luis",
                            "apellido": "Martínez",
                            "telefono": "1122334455",
                            "fecha_nacimiento": "2000-01-01"
                          }
                        }
                      }
                    }
                  },
                  "required": true
                },
                "responses": {
                  "201": {
                    "description": "Paciente creado exitosamente",
                    "content": {
                      "application/json": {
                        "schema": {
                          "$ref": "#/components/schemas/Paciente"
                        },
                        "examples": {
                          "example-1": {
                            "value": {
                              "id_numeroCedula": 3,
                              "nombre": "Luis",
                              "apellido": "Martínez",
                              "telefono": "1122334455",
                              "fecha_nacimiento": "2000-01-01"
                            }
                          }
                        }
                      }
                    }
                  },
                  "400": {
                    "description": "El número de cédula ya existe",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "El número de cédula ya existe"
                            }
                          }
                        }
                      }
                    }
                  },
                  "500": {
                    "description": "Error del servidor",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Hubo un error al crear el paciente"
                            }
                          }
                        }
                      }
                    }
                  }
                }
            }
        },
        "/pacientes/{id}": {
            "get": {
                "summary": "Obtiene un paciente por ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID del paciente",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Paciente"
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "id_numeroCedula": 123,
                                            "nombre": "Pedro",
                                            "apellido": "García",
                                            "telefono": "1234567890",
                                            "fecha_nacimiento": "1990-01-01"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Paciente no encontrado"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener el paciente"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Actualiza un paciente",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID del paciente",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Paciente"
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "nombre": "Pedro Actualizado",
                                        "apellido": "García Actualizado",
                                        "telefono": "0987654321",
                                        "fecha_nacimiento": "1991-01-01"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Paciente actualizado exitosamente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Paciente"
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "id_numeroCedula": 111,
                                            "nombre": "Pedro Actualizado",
                                            "apellido": "García Actualizado",
                                            "telefono": "0987654321",
                                            "fecha_nacimiento": "1991-01-01"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Paciente no encontrado"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al actualizar el paciente"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Elimina un paciente",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID del paciente",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paciente eliminado exitosamente",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Paciente eliminado exitosamente"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Paciente no encontrado"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al eliminar el paciente"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/citas": {
            "get": {
                "summary": "Obtiene todas las citas",
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Cita"
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": [
                                            {
                                                "fecha_hora": "2023-11-26T17:30:00.000Z",
                                                "id_profesional": 1,
                                                "id_numeroCedula": 123
                                            },
                                            {
                                                "fecha_hora": "2023-11-26T17:30:00.000Z",
                                                "id_profesional": 2,
                                                "id_numeroCedula": 321
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener las citas"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Actualiza una cita",
                "parameters": [
                  {
                    "name": "profesional",
                    "in": "query",
                    "required": true,
                    "description": "Profesional de la cita",
                    "schema": {
                      "type": "integer"
                    }
                  },
                  {
                    "name": "paciente",
                    "in": "query",
                    "required": true,
                    "description": "Paciente de la cita",
                    "schema": {
                      "type": "integer"
                    }
                  },
                  {
                    "name": "fecha",
                    "in": "query",
                    "required": true,
                    "description": "Fecha de la cita",
                    "schema": {
                      "type": "string",
                      "format": "date-time"
                    }
                  }
                ],
                "requestBody": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Cita"
                      },
                      "examples": {
                        "example-1": {
                          "value": {
                            "fecha_hora": "2023-11-26T17:30:00.000Z",
                            "id_profesional": 2,
                            "id_numeroCedula": 2
                          }
                        }
                      }
                    }
                  },
                  "required": true
                },
                "responses": {
                  "200": {
                    "description": "Cita actualizada exitosamente",
                    "content": {
                      "application/json": {
                        "schema": {
                          "$ref": "#/components/schemas/Cita"
                        },
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Cita actualizada exitosamente"
                            }
                          }
                        }
                      }
                    }
                  },
                  "404": {
                    "description": "Cita no encontrada",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Cita no encontrada"
                            }
                          }
                        }
                      }
                    }
                  },
                  "500": {
                    "description": "Error del servidor",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Hubo un error al actualizar la cita"
                            }
                          }
                        }
                      }
                    }
                  }
                }
             }
           },
           "/citas/crear": {
            "post": {
                "summary": "Crea una nueva cita",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Cita"
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "fecha_hora": "2023-11-26T17:30:00.000Z",
                                        "id_profesional": 3,
                                        "id_numeroCedula": 456
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Cita creada exitosamente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Cita"
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "fecha_hora": "2023-11-26T17:30:00.000Z",
                                            "id_profesional": 3,
                                            "id_numeroCedula": 3
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al crear la cita"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/citas/{fecha}": {
            "delete": {
                "summary": "Elimina una cita",
                "parameters": [
                    {
                      "name": "fecha",
                      "in": "path",
                      "required": true,
                      "description": "Fecha de la cita",
                      "schema": {
                        "type": "string",
                        "format": "date-time"
                      }
                    }
                  ],
                "responses": {
                  "200": {
                    "description": "Cita eliminada exitosamente",
                    "content": {
                      "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Cita"
                        },
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Cita eliminada exitosamente"
                            }
                          }
                        }
                      }
                    }
                  },
                  "404": {
                    "description": "Cita no encontrada",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Cita no encontrada"
                            }
                          }
                        }
                      }
                    }
                  },
                  "500": {
                    "description": "Error del servidor",
                    "content": {
                      "application/json": {
                        "examples": {
                          "example-1": {
                            "value": {
                              "message": "Hubo un error al eliminar la cita"
                            }
                          }
                        }
                      }
                    }
                  }
                }
            },
            "get": {
                "summary": "Obtiene una cita única por fecha",
                "parameters": [
                    {
                      "name": "fecha",
                      "in": "path",
                      "required": true,
                      "description": "Fecha de la cita",
                      "schema": {
                        "type": "string",
                        "format": "date-time"
                      }
                    }
                  ],
                "responses": {
                    "200": {
                        "description": "Operación exitosa",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Cita"
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "fecha_hora": "2023-11-26T17:30:00.000Z",
                                            "id_profesional": 1,
                                            "id_numeroCedula": 1
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Cita no encontrada",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Cita no encontrada"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "message": "Hubo un error al obtener la cita"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
       }   
    },
    "components": {
    "schemas": {
        "Doctor": {
            "type": "object",
            "properties": {
              "id_profesional": {
                "type": "integer",
                "description": "ID del doctor"
              },
              "nombre": {
                "type": "string",
                "description": "Nombre del doctor"
              },
              "apellido": {
                "type": "string",
                "description": "Apellido del doctor"
              },
              "correo": {
                "type": "string",
                "description": "Correo del doctor",
                "format": "email"
              },
              "id_especialidad": {
                "type": "integer",
                "description": "ID Especialidad del doctor"
              },
              "consultorio": {
                "type": "integer",
                "description": "Número de consultorio del doctor"
              }
            },
            "required": [
              "id_profesional",
              "nombre",
              "apellido",
              "correo",
              "id_especialidad",
              "consultorio"
            ]
          },
          "Paciente": {
            "type": "object",
            "properties": {
              "id_numeroCedula": {
                "type": "integer",
                "description": "ID del paciente"
              },
              "nombre": {
                "type": "string",
                "description": "Nombre del paciente"
              },
              "apellido": {
                "type": "string",
                "description": "Apellido del paciente"
              },
              "telefono": {
                "type": "string",
                "description": "Teléfono del paciente"
              },
              "fecha_nacimiento": {
                "type": "string",
                "format": "date",
                "description": "Fecha de nacimiento del paciente"
              }
            },
            "required": [
              "id_numeroCedula",
              "nombre",
              "apellido",
              "telefono",
              "fecha_nacimiento"
            ]
          },
            "Cita": {
                "type": "object",
                "properties": {
                    "fecha_hora": {
                        "type": "string",
                        "format": "date-time",
                        "description": "Fecha y hora de la cita"
                    },
                    "id_profesional": {
                        "type": "integer",
                        "description": "ID del doctor"
                    },
                    "id_numeroCedula": {
                        "type": "integer",
                        "description": "ID del paciente"
                    }
                },
                "required": [
                    "fecha_hora",
                    "id_profesional",
                    "id_numeroCedula"
                ]
            }
        }
    }
}
